---
title: "loopedmice"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(viridis)
library(dplyr)
library(hrbrthemes)
library(vioplot)
library(vctrs)
new <- read.csv("Mouse_Info - Sheet1.csv")
new <- new %>%
  # filter(! is.na(Treatment)) %>%
  # filter(Treatment != "") %>%
  # # mutate(mouse = case_when(
  # #   Genotype == "APOE2" | Genotype == "APOE22" ~ "APOE2",
  # #   Genotype == "APOE3" | Genotype == "APOE33" ~ "APOE3",
  # #   Genotype == "APOE4" | Genotype == "APOE44" ~ "APOE4",
  # #   Genotype == "CVN" ~ "CVN"
  # # )) %>%
  # group_by(Treatment)
view(new)

t1<-new %>%
filter(Time.Point==1)

t2<-new %>%
filter(Time.Point==2)

t3<-new %>%
filter(Time.Point==3)

times<-data.frame(c(t1), c(t2), c(t3))
```


 ## Adjusted p-values for multiple comparisons
# ```{r corrections, echo = FALSE}
 #   p.adjust(corrRight$pval, method = "fdr", n = )
# ```


```{r Brain, echo = FALSE}
    dodge <- position_dodge(width = 1)
    for (i in 1:3)
    {
      t<-new %>%
        filter(Time.Point==i)
          abc <- ggplot(data = t, aes(factor(Treatment), BrainVolume, fill = Genotype)) +
            geom_violin(inherit.aes=TRUE,position=dodge, alpha=0.5) +
            geom_boxplot(color="black", outlier.color="black", width=0.2, alpha=.6, position=dodge) +
            geom_dotplot(binaxis='y', stackdir='center', dotsize=0.6, alpha=0.6, position=dodge) +
            theme_classic()+

              labs(x = "Treatment",
                    y = "",
                    title = "Brain Volume",
                    subtitle = i)
          print(abc)

              mylm <- lm(BrainVolume ~ Treatment * Genotype * Time.Point, t)
              summary(mylm)
              anova(mylm)
              
          print(mylm)
          print(summary(mylm))
          print(anova(mylm))
          
    }
    
    #mylm_cut <- subset(mylm, select=c('F value', 'Pr(>F)'))
    #write.csv(mylm_cut,'/Users/', row_names=TRUE)
```

```{r X1, echo = FALSE}
    dodge <- position_dodge(width = 1)
    for (j in 7:172)
      { 
        for (i in 1:3)
          {
            t<-new %>%
              filter(Time.Point==i)
        
              genotype<-t[,4]
              treatment<-t[,5]  
              volumes<-t[,j]
              region<-t[j]
                abc <- ggplot() +
                    geom_violin(aes(x=treatment, y=volumes, fill=genotype), position=dodge, alpha=0.5) +
                    geom_boxplot(data=t, aes(x=treatment, y=volumes, fill=genotype), color="black", outlier.color="black", width=0.2, alpha=.6, position=dodge) +
                    geom_dotplot(data=t, aes(x=treatment, y=volumes, fill=genotype), binaxis='y', stackdir='center', dotsize=0.6, alpha=0.6, position=dodge) +
                    theme_classic()+
      
                    labs(x = "Treatment",
                          y = "",
                          title = j-6,
                          subtitle = i)
                print(abc)
      
                    mylm <- lm(volumes ~ treatment * genotype * Time.Point, t)
                     summary(mylm)
                     anova(mylm)
                 
                 print(mylm)
                 print(summary(mylm))
                 print(anova(mylm))
              }
                  
            }
    
    #mylm_cut <- subset(mylm, select=c('F value', 'Pr(>F)'))
    #write.csv(mylm_cut,'/Users/', row_names=TRUE)
```

```{r X1000, echo = FALSE}
    dodge <- position_dodge(width = 1)
    for (j in 173:339)
      { 
        for (i in 1:3)
          {
            t<-new %>%
              filter(Time.Point==i)
        
              genotype<-t[,4]
              treatment<-t[,5]  
              volumes<-t[,j]
              region<-t[j]
                abc <- ggplot() +
                    geom_violin(aes(x=treatment, y=volumes, fill=genotype), position=dodge, alpha=0.5) +
                    geom_boxplot(data=t, aes(x=treatment, y=volumes, fill=genotype), color="black", outlier.color="black", width=0.2, alpha=.6, position=dodge) +
                    geom_dotplot(data=t, aes(x=treatment, y=volumes, fill=genotype), binaxis='y', stackdir='center', dotsize=0.6, alpha=0.6, position=dodge) +
                    theme_classic()+
      
                    labs(x = "Treatment",
                          y = "",
                          title = j+828,
                          subtitle = i)
                print(abc)
      
                    mylm <- lm(volumes ~ treatment * genotype * Time.Point, t)
                     summary(mylm)
                     anova(mylm)
                 
                 print(mylm)
                 print(summary(mylm))
                 print(anova(mylm))
              }
                  
            }
    
    #mylm_cut <- subset(mylm, select=c('F value', 'Pr(>F)'))
    #write.csv(mylm_cut,'/Users/', row_names=TRUE)
```