---
title: "loopedmice"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(viridis)
library(dplyr)
library(hrbrthemes)
library(vioplot)
library(vctrs)
library(emmeans)
library(tidyverse)
library(gridExtra)
library(scales)
library(ggplot2)
library(cowplot)
library(gplots)
library(tidyverse)
library(patternplot)
library(lme4)
library(visreg)
library(tidyr)
library(magrittr) 
library(dplyr)
library(ggpubr)
library(lme4)
library(lsmeans)
library(emmeans)
library(multcomp)
library(zoo)
new <- read.csv("MouseInfoRevised.csv")
red <- read.csv("MouseInfoRevised.csv", header=FALSE)
new$Time.Point <- as.factor(new$Time.Point)
new <- new %>%
  # filter(! is.na(Treatment)) %>%
  # filter(Treatment != "") %>%
  # # mutate(mouse = case_when(
  # #   Genotype == "APOE2" | Genotype == "APOE22" ~ "APOE2",
  # #   Genotype == "APOE3" | Genotype == "APOE33" ~ "APOE3",
  # #   Genotype == "APOE4" | Genotype == "APOE44" ~ "APOE4",
  # #   Genotype == "CVN" ~ "CVN"
  # # )) %>%
  # group_by(Treatment)
view(new)

t1<-new %>%
filter(Time.Point==1)

t2<-new %>%
filter(Time.Point==2)

t3<-new %>%
filter(Time.Point==3)

times<-data.frame(c(t1), c(t2), c(t3))
```


 ## Adjusted p-values for multiple comparisons
# ```{r corrections, echo = FALSE}
 #   p.adjust(corrRight$pval, method = "fdr", n = )
# ```


```{r Brain, echo = FALSE}
    dodge <- position_dodge(width = 1)
    for (i in 1:3)
    {
      t<-new %>%
        filter(Time.Point==i)
          abc <- ggplot(data = t, aes(factor(Treatment), BrainVolume, fill = Genotype)) +
            geom_violin(inherit.aes=TRUE,position=dodge, alpha=0.5) +
            geom_boxplot(color="black", outlier.color="black", width=0.2, alpha=.6, position=dodge) +
            geom_dotplot(binaxis='y', stackdir='center', dotsize=0.6, alpha=0.6, position=dodge) +
            theme_classic()+

              labs(x = "Treatment",
                    y = "",
                    title = "Brain Volume",
                    subtitle = i)
          print(abc)
    }
             
    
    #mylm_cut <- subset(mylm, select=c('F value', 'Pr(>F)'))
    #write.csv(mylm_cut,'/Users/', row_names=TRUE)
```

```{r X1, echo = FALSE}
    dodge <- position_dodge(width = 1)
    for (j in 6:121)
      { 
      volumenotime<-new[,j]
        for (i in 1:3)
          {
            t<-new %>%
              filter(Time.Point==i)

              genotype<-t[,4]
              treatment<-t[,5]  
              volumes<-t[,j]
              region<-red[1,]
                abc <- ggplot() +
                    geom_violin(aes(x=treatment, y=volumes, fill=genotype), position=dodge, alpha=0.5) +
                    geom_boxplot(data=t, aes(x=treatment, y=volumes, fill=genotype), color="black", outlier.color="black", width=0.2, alpha=.6, position=dodge) +
                    geom_dotplot(data=t, aes(x=treatment, y=volumes, fill=genotype), binaxis='y', stackdir='center', dotsize=0.6, alpha=0.6, position=dodge) +
                    theme_classic()+
      
                    labs(x = "Treatment",
                          y = "",
                          title = region[j],
                          subtitle = i)
                print(abc)
                
  
        
        }
               
                mylm <- lm(volumenotime ~ Treatment + Genotype + Time.Point, new)
                summary(mylm)
                anova(mylm)
                
                 # #post hoc tests
            
                summary(glht(mylm, emm(pairwise ~ Genotype*Treatment, adjust="sidak"))) #consider save to file
                res<-summary(glht(mylm, emm(pairwise ~ Genotype*Treatment))) #consider save to file
                 #summary(as.glht(pairs(lm_CPu_VOL.emm), by = NULL))
                 # 
                summary(glht(mylm, emm(pairwise ~ Genotype+Treatment | Time.Point)))
                summary(glht(mylm, emm(pairwise ~ Treatment+Time.Point | Genotype)))
                summary(glht(mylm, emm(pairwise ~ Genotype+Time.Point | Treatment)))
                 # 
                
                print(region[j])

    
    }

  
                  
            
    
    #mylm_cut <- subset(mylm, select=c('F value', 'Pr(>F)'))
    #write.csv(mylm_cut,'/Users/', row_names=TRUE)
```

